# Constants
title: "Burrows Report"
description: "Facts for people on the go and in the know"
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

theme: minima

gems:
  - jekyll-feed
  - jekyll-paginate

paginate: 3

paginate_path: page:num/

disqus:
  shortname: burrowsreport

google_analytics: UA-106769019-1

exclude:
  - Gemfile
  - Gemfile.lock
exclude: [vendor]

