# Constants
title: "Burrows Report"
description: "Facts for people on the go and in the know"
#url: "https://jaredsburrows.github.io/project-sea-turtle"
url: ""

permalink: /:title/

# Build settings
markdown: kramdown

theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 3

paginate_path: page:num/

disqus:
  shortname: burrowsreport

google_analytics: UA-106769019-1

include:
  - '.well-known'

exclude:
  - 'node_modules'
  - 'scripts'
  - 'vendor'
  - .editorconfig
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.txt
  - CNAME
  - jekyll.thor
