name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7

      - name: Cache dependencies
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.rvm
          key: ${{ runner.os }}-bundler
          restore-keys: ${{ runner.os }}-bundler

      - name: Configure Ruby
        uses: ruby/setup-ruby@v1.193.0
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install Dependencies
        run: |
          gem install stringex
          gem install json
          gem install thor
          bundle install

      - name: Add new posts here
        run: |
          thor jekyll:new

      - name: Build the Project
        run: |
          bundle exec jekyll build

      - name: Publish Website
        uses: peaceiris/actions-gh-pages@v3.9.3
        if: github.repository == 'jaredsburrows/project-sea-turtle' && github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          user_name: "Github Actions"
          user_email: "action@github.com"
