name: build

on:
  push:
    branches:
      - gh-pages
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.5.2

      - name: Cache dependencies
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.rvm
          key: ${{ runner.os }}-bundler
          restore-keys: ${{ runner.os }}-bundler

      - name: Configure Ruby
        uses: ruby/setup-ruby@v1.146.0
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install Dependencies
        run: |
          gem install stringex
          gem install json
          gem install thor
          bundle install

      - name: Build the Project
        run: |
          bundle exec jekyll build

      - name: Add new posts here
        run: |
          thor jekyll:new
